console.log("This is my first code file")
console.log("give by ganesh")
console.log("this is from Anusha")
console.log("this is from Harika")
console.log("this is from anjani")
console.log("this is from acthuthasai")
console.log("credo")
console.log("coding sastra")
console.log("gud morning all")
console.log("github")
console.log("full stack developers")
console.log("reactjs")
console.log("registraion form")